# Archivo: .github/workflows/locust-test.yml

name: Pruebas de Carga con Locust

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-locust-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar Locust y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install locust
    
    - name: Ejecutar pruebas de carga con Locust
      run: |
        locust -f locustfile.py --headless --host=https://demowebshop.tricentis.com/ --users 50 --spawn-rate 10 --run-time 60s --html report-locust.html

    - name: Subir el reporte de carga como un artefacto
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: locust-reporte
        path: report-locust.html
