name: Security Scan with ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Baseline Scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: ZAP Baseline Scan
        uses: docker://ghcr.io/zaproxy/zaproxy:stable
        with:
          args: zap-baseline.py -t http://testphp.vulnweb.com/ -r reports/zap-report.html -w reports/zap-report.md
        continue-on-error: true

      - name: Upload Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
          path: reports/
