name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    permissions:
      contents: read
      # Desactivamos explícitamente el permiso de 'issues' para que la acción de ZAP no pueda
      # crear ni actualizar incidencias, resolviendo el error de "Resource not accessible".
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://testphp.vulnweb.com/'
          fail_action: false
        env:
          GH_TOKEN: ''

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          # Se ha cambiado el nombre del artefacto a "zap-scan-results" para evitar errores de validación.
          name: zap-scan-results
          path: report_html.html
          retention-days: 5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Agrega esta línea para instalar la librería
          pip install -r requirements.txt
