name: CI con Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_pytest_tests:
    strategy:
      matrix:
        browser: [chrome, firefox]
        
    runs-on: ubuntu-latest
    name: "Run Pytest Tests (${{ matrix.browser }})"
    needs: []
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest pytest-html requests
          
      - name: Run Pytest Tests
        # Pasamos el nombre del navegador como una variable de entorno
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          # 1. Ejecutar las pruebas de API
          pytest tests/test_api_refactored.py --html=report_api.html --self-contained-html
          # 2. Ejecutar las pruebas de Selenium
          pytest tests/test_login_multiuser.py --html=report_selenium.html --self-contained-html
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: "pytest-report-${{ matrix.browser }}"
          path: '*.html'