name: ZAP Full Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Full Scan the web application
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0 # Versión corregida
        with:
          target: 'http://testphp.vulnweb.com/'
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: report.html
          retention-days: 5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver-autoinstaller pytest requests
  run_pytest_tests:
    runs-on: ubuntu-latest
    name: Run Pytest Tests
    needs: zap_full_scan # Esto asegura que este job se ejecute después del escaneo de ZAP
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver-autoinstaller pytest
          
      - name: Run Pytest Tests
        run: |
          pytest tests/

      - name: Run Pytest Tests
        run: |
          pytest --html=report.html --self-contained-html
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html