name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Esto es necesario para obtener un checkout limpio del repositorio.
          fetch-depth: 0

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://testphp.vulnweb.com/'
          # Deshabilita la creación automática de incidencias para evitar errores de permisos.
          issue_unverified: false
          
      # Se carga el reporte HTML por defecto.
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report_html.html
          retention-days: 5
