name: Pruebas de Python y Escaneo de Seguridad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  complete_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        
    - name: Instalar dependencias
      run: |
        echo "Instalando dependencias..."
        python -m pip install --upgrade pip
        pip install pytest requests selenium
        
    - name: Ejecutar pruebas de Pytest
      run: |
        echo "Ejecutando pruebas de Pytest..."
        pytest
    
    # Construye la imagen de Docker de tu aplicación.
    - name: Construir la imagen de Docker de la aplicación
      run: |
        docker build -t mi-app-web .

    # Crea una red de Docker para que los contenedores puedan comunicarse.
    - name: Crear red de Docker y ejecutar el contenedor de la aplicación
      run: |
        docker network create zap-scan-network
        docker run -d --rm --name mi-app --network zap-scan-network mi-app-web
        
        echo "Esperando 30 segundos para que el contenedor de la aplicación inicie completamente..."
        sleep 30
        
    # Ejecuta ZAP manualmente dentro de la misma red de Docker.
    - name: Ejecutar escaneo de seguridad con ZAP
      run: |
        docker run --rm --network zap-scan-network \
          -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://mi-app:5000 \
          -J report_json.json \
          -r report_html.html
          
    - name: Subir reporte de seguridad (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-html
        path: report_html.html
