name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This is required to get a clean checkout of the repository,
          # and not just a single commit.
          fetch-depth: 0

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://testphp.vulnweb.com/'
          # ZAP está diseñado para crear los reportes en el directorio de trabajo
          # por defecto, así que le decimos que lo haga.
          cmd_options: '-r zap-report.html'
          
      # Este paso nos mostrará todos los archivos en el directorio de trabajo.
      # Lo necesitamos para encontrar el reporte.
      - name: List Files for Debugging
        run: ls -R

      # Usaremos una ruta genérica para ver si el reporte está ahí.
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap-report.html
          retention-days: 5
