# Archivo: .github/workflows/main.yml
name: Pruebas de Python y Seguridad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests selenium
        
    - name: Ejecutar pruebas de Pytest
      run: |
        echo "Ejecutando todas las pruebas en la carpeta 'tests'..."
        pytest

  # Tarea de escaneo de seguridad (corregida)
  zap_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Escanear la aplicación web con OWASP ZAP
        uses: zaproxy/action@v0.8.0
        with:
          # Aquí debes poner la URL de tu aplicación en el servidor local o la de tu sitio web publicado.
          target: 'http://localhost:5000'
          # Tipo de escaneo. El 'baseline_scan' es un escaneo rápido.
          cmd: 'baseline'
          # Puedes incluir las siguientes opciones para personalizar el escaneo:
          # report_html: true
          # rules_file: '.zap/rules.txt' # Opcional: un archivo para ignorar reglas.
