name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    # Usamos solo el permiso de lectura de contenido, ya que no crearemos incidencias.
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://testphp.vulnweb.com/'
          # Evita que la acción de ZAP falle si encuentra vulnerabilidades.
          fail_action: false
          # Deshabilita completamente la creación de incidencias.
          issue_title: ''
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          # Usa un nombre de artefacto válido. El guión bajo a veces causa problemas.
          name: zap-security-report
          # El nombre del archivo por defecto que genera la acción de ZAP.
          path: report_html.html
          retention-days: 5
