name: Pruebas de Python y Escaneo de Seguridad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  complete_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        
    - name: Instalar dependencias
      run: |
        echo "Instalando dependencias..."
        python -m pip install --upgrade pip
        pip install pytest requests selenium
        
    - name: Ejecutar pruebas de Pytest
      run: |
        echo "Ejecutando pruebas de Pytest..."
        pytest
    
    # Construye la imagen de Docker de tu aplicación.
    - name: Construir la imagen de Docker de la aplicación
      run: |
        docker build -t mi-app-web .

    # Crea una red de Docker para que los contenedores puedan comunicarse.
    - name: Crear red de Docker y ejecutar el contenedor de la aplicación
      run: |
        docker network create zap-scan-network
        docker run -d --rm --name mi-app --network zap-scan-network mi-app-web
        
        echo "Esperando 30 segundos para que el contenedor de la aplicación inicie completamente..."
        sleep 30
        
    # Ejecuta ZAP en un nuevo contenedor y genera los reportes internamente.
    # Ahora creamos el directorio '/zap/wrk' antes del escaneo.
    - name: Ejecutar escaneo de seguridad con ZAP
      run: |
        docker run --rm --name zap-scanner --network zap-scan-network \
          ghcr.io/zaproxy/zaproxy:stable \
          /bin/bash -c "mkdir -p /zap/wrk && zap-baseline.py -t http://mi-app:5000 -J /zap/wrk/report_json.json -r /zap/wrk/report_html.html"
        
    # Copia los archivos de reporte del contenedor a tu sistema de archivos de GitHub Actions.
    - name: Copiar reportes de ZAP
      run: |
        docker cp zap-scanner:/zap/wrk/report_json.json .
        docker cp zap-scanner:/zap/wrk/report_html.html .
          
    - name: Subir reporte de seguridad (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: zap-report-html
        path: report_html.html
