# Archivo: .github/workflows/main.yml
name: Pruebas de Python y Seguridad

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests selenium
        
    - name: Ejecutar pruebas de Pytest
      run: |
        echo "Ejecutando todas las pruebas en la carpeta 'tests'..."
        pytest

  # Tarea de escaneo de seguridad (versión 4, corregida)
  zap_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Iniciar la aplicación web de prueba
        # Reemplaza 'app.py' con el nombre de tu archivo principal si es diferente.
        run: |
          python app.py &
          sleep 10
        
      - name: Escanear la aplicación con OWASP ZAP
        # Esta es la línea corregida. Apunta a la acción oficial y moderna.
        uses: zaproxy/zap-action@v2.0.0
        with:
          # Aquí debes poner la URL de tu aplicación que se ejecuta localmente.
          target: 'http://localhost:5000'
          # Tipo de escaneo. El 'baseline_scan' es un escaneo rápido.
          cmd: 'baseline'
          # Puedes incluir las siguientes opciones para personalizar el escaneo:
          # report_html: true
          # rules_file: '.zap/rules.txt' # Opcional: un archivo para ignorar reglas.
