name: CI con Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_pytest_tests:
    runs-on: ubuntu-latest
    name: Run Pytest Tests
    needs: []
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python and Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver-autoinstaller pytest pytest-html requests
          
      - name: Run Pytest Tests
        run: |
          pytest --html=report.html --self-contained-html
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: '*.html'