name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This is required to get a clean checkout of the repository,
          # and not just a single commit.
          fetch-depth: 0

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-r reports/zap-report.html'
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: reports/
          retention-days: 5
