name: ZAP Full Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Full Scan the web application
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://testphp.vulnweb.com/'
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: report.html
          retention-days: 5