name: CI con Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_pytest_tests:
    # Agrega la estrategia de matriz aquí
    strategy:
      matrix:
        browser: [chrome, firefox] # Define los navegadores para los que se ejecutará el job
        
    runs-on: ubuntu-latest
    # Nombre del job dinámico para mostrar el navegador
    name: "Run Pytest Tests (${{ matrix.browser }})"
    needs: []
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python and Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Cambiamos chromedriver-autoinstaller por webdriver-manager para manejar varios navegadores
          pip install selenium webdriver-manager pytest pytest-html requests
          
      - name: Run Pytest Tests
        # Pasamos el nombre del navegador como una variable de entorno
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          pytest --html=report.html --self-contained-html
          
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          # Nombre del reporte dinámico para no sobrescribir
          name: "pytest-report-${{ matrix.browser }}"
          path: '*.html'